spring.application.name=legacy-supplier-portal

# --- Base H2 en memoire ---
spring.datasource.url=jdbc:h2:mem:supplierportal
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Schema genere automatiquement a chaque demarrage
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# data.sql doit s'executer APRES la creation du schema par Hibernate
spring.jpa.defer-datasource-initialization=true

# Console H2 : http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Port HTTP standard
server.port=8080
